// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoTienda.Data;

namespace ProyectoTienda.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20200829230600_BaseDatos")]
    partial class BaseDatos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProyectoTienda.Models.CompraCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cantidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompraCliente");
                });

            modelBuilder.Entity("ProyectoTienda.Models.Direccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CallePrincipal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CalleSecundari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompraClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("DueñoTiendaId")
                        .HasColumnType("int");

                    b.Property<string>("Referencia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompraClienteId");

                    b.HasIndex("DueñoTiendaId");

                    b.ToTable("Direccion");
                });

            modelBuilder.Entity("ProyectoTienda.Models.DueñoTienda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cantidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DueñoTienda");
                });

            modelBuilder.Entity("ProyectoTienda.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CompraClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DueñoTiendaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompraClienteId");

                    b.HasIndex("DueñoTiendaId");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("ProyectoTienda.Models.Direccion", b =>
                {
                    b.HasOne("ProyectoTienda.Models.CompraCliente", null)
                        .WithMany("Direccion")
                        .HasForeignKey("CompraClienteId");

                    b.HasOne("ProyectoTienda.Models.DueñoTienda", null)
                        .WithMany("Direccion")
                        .HasForeignKey("DueñoTiendaId");
                });

            modelBuilder.Entity("ProyectoTienda.Models.Producto", b =>
                {
                    b.HasOne("ProyectoTienda.Models.CompraCliente", null)
                        .WithMany("Productos")
                        .HasForeignKey("CompraClienteId");

                    b.HasOne("ProyectoTienda.Models.DueñoTienda", null)
                        .WithMany("Productos")
                        .HasForeignKey("DueñoTiendaId");
                });
#pragma warning restore 612, 618
        }
    }
}
